---
###### Variables to be passed to this playbook ######
#
#  username: [BIG-IP username]
#  password: [BIG-IP password]
#  appsvcs_ver: [iApp version as reported via BIG-IP REST API]
#
#  Examples:
#  username: admin
#  password: admin
#  appsvcs_major: "2.0"
#  appsvcs_pres: "001"
#  appsvcs_ver: appsvcs_integration_v{{ appsvcs_major }}_{{ appsvcs_pres }}
#
# Author: Nathan Pearce
###### https://github.com/npearce/F5-iApps_and_Ansible-playbooks ######

- name: Retrieve a list of iApps installed on F5 BIG-IP
  hosts: bigips
  connection: local
  gather_facts: no
  tasks:

  - name: Query iApp resource via BIG-IP REST API
    uri:
      url: https://{{inventory_hostname}}/mgmt/tm/cloud/templates/iapp/
      validate_certs: no
      user: "{{ username }}"
      password: "{{ password }}"
      return_content: yes
    register: iapps_list

## Example of how to look for a specific string in the response using a 'when' statement.
  - name: Check {{ appsvcs_ver }} IS in response
    debug: msg="{{ appsvcs_ver }} found"
    when: '"{{ appsvcs_ver }}" in (iapps_list.content|from_json)["items"]'

## Example of check a specific string is NOT in the response using a 'when' statement.
  - name: Check {{ appsvcs_ver }} IS NOT in response
    debug: msg="'{{ appsvcs_ver }}' not found"
    when: '"{{ appsvcs_ver }}" not in (iapps_list.content|from_json)["items"]'
